import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-screen bg-gray-100`}
      >
        <header>
          <Link href="/">Documentation</Link>
          <Link href="/shiritori">Shiritori</Link>
          <Link href="/form">Form</Link>
          <Link href="/dropdown">Dropdown</Link>
        </header>
        {children}
        <div id="modal-container">

        </div>
      </body>
    </html>
  );
}
